=begin
#The SMS Works API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require "uri"

module SwaggerClient
  class UtilsApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end

    # 
    # Returns 'Hello' to the caller
    # @param [Hash] opts the optional parameters
    # @option opts [String] :name The name of the person to whom to say hello
    # @return [HelloWorldResponse]
    def hello(opts = {})
      data, _status_code, _headers = hello_with_http_info(opts)
      return data
    end

    # 
    # Returns &#39;Hello&#39; to the caller
    # @param [Hash] opts the optional parameters
    # @option opts [String] :name The name of the person to whom to say hello
    # @return [Array<(HelloWorldResponse, Fixnum, Hash)>] HelloWorldResponse data, response status code and response headers
    def hello_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: UtilsApi.hello ..."
      end
      # resource path
      local_var_path = "/utils/hello"

      # query parameters
      query_params = {}
      query_params[:'name'] = opts[:'name'] if !opts[:'name'].nil?

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json;charset=UTF-8'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = []
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'HelloWorldResponse')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: UtilsApi#hello\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
