=begin
#The SMS Works API

#The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed UK messages are refunded.

The version of the OpenAPI document: 1.9.0
Contact: support@thesmsworks.co.uk
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.1.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::CreditsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CreditsApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::CreditsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CreditsApi' do
    it 'should create an instance of CreditsApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::CreditsApi)
    end
  end

  # unit tests for credits_balance_get
  # Returns the number of credits currently available on the account
  # @param [Hash] opts the optional parameters
  # @return [CreditsResponse]
  describe 'credits_balance_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
