=begin
#The SMS Works API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::MessagesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'MessagesApi' do
  before do
    # run before each test
    @instance = SwaggerClient::MessagesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MessagesApi' do
    it 'should create an instance of MessagesApi' do
      expect(@instance).to be_instance_of(SwaggerClient::MessagesApi)
    end
  end

  # unit tests for cancel_scheduled_job
  # 
  # Cancels a scheduled SMS message
  # @param messageid The ID of the message you would like returned
  # @param [Hash] opts the optional parameters
  # @return [CancelledMessageResponse]
  describe 'cancel_scheduled_job test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_message_by_id
  # 
  # Retrieve a logged message by the message ID
  # @param messageid The ID of the message you would like returned
  # @param [Hash] opts the optional parameters
  # @return [MessageResponse]
  describe 'get_message_by_id test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_messages
  # 
  # Get messages matching your search criteria
  # @param query 
  # @param [Hash] opts the optional parameters
  # @return [MessagesResponse]
  describe 'get_messages test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for schedule_message
  # 
  # Schedules an SMS message to be sent at the date-time you specify
  # @param sms_message Message properties
  # @param [Hash] opts the optional parameters
  # @return [ScheduledMessageResponse]
  describe 'schedule_message test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for send_message
  # 
  # Sends an SMS message
  # @param sms_message Message properties
  # @param [Hash] opts the optional parameters
  # @return [SendMessageResponse]
  describe 'send_message test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
