=begin
#The SMS Works API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::ScheduledBatchResponse
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ScheduledBatchResponse' do
  before do
    # run before each test
    @instance = SwaggerClient::ScheduledBatchResponse.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ScheduledBatchResponse' do
    it 'should create an instance of ScheduledBatchResponse' do
      expect(@instance).to be_instance_of(SwaggerClient::ScheduledBatchResponse)
    end
  end
  describe 'test attribute "batchid"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "status"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

