=begin
#The SMS Works API

#The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed UK messages are refunded.

The version of the OpenAPI document: 1.9.0
Contact: support@thesmsworks.co.uk
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.1.0

=end

# Common files
require 'openapi_client/api_client'
require 'openapi_client/api_error'
require 'openapi_client/version'
require 'openapi_client/configuration'

# Models
require 'openapi_client/models/batch_message'
require 'openapi_client/models/batch_message_response'
require 'openapi_client/models/cancelled_message_response'
require 'openapi_client/models/credits_response'
require 'openapi_client/models/deleted_message_response'
require 'openapi_client/models/error_model'
require 'openapi_client/models/extended_error_model'
require 'openapi_client/models/message'
require 'openapi_client/models/message_metadata'
require 'openapi_client/models/message_response'
require 'openapi_client/models/message_response_failurereason'
require 'openapi_client/models/meta_data'
require 'openapi_client/models/otp'
require 'openapi_client/models/otp_response'
require 'openapi_client/models/otp_verify'
require 'openapi_client/models/otp_verify_response'
require 'openapi_client/models/query'
require 'openapi_client/models/query_metadata'
require 'openapi_client/models/scheduled_batch_response'
require 'openapi_client/models/scheduled_message'
require 'openapi_client/models/scheduled_message_response'
require 'openapi_client/models/scheduled_messages_response'
require 'openapi_client/models/scheduled_messages_response_message'
require 'openapi_client/models/send_message_response'
require 'openapi_client/models/test_response'

# APIs
require 'openapi_client/api/batch_messages_api'
require 'openapi_client/api/credits_api'
require 'openapi_client/api/messages_api'
require 'openapi_client/api/one_time_password_api'
require 'openapi_client/api/utils_api'

module OpenapiClient
  class << self
    # Customize default settings for the SDK using block.
    #   OpenapiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
