=begin
#The SMS Works API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

# Common files
require 'swagger_client/api_client'
require 'swagger_client/api_error'
require 'swagger_client/version'
require 'swagger_client/configuration'

# Models
require 'swagger_client/models/api_key_response'
require 'swagger_client/models/batch_message'
require 'swagger_client/models/batch_message_response'
require 'swagger_client/models/cancelled_message_response'
require 'swagger_client/models/error_model'
require 'swagger_client/models/hello_world_response'
require 'swagger_client/models/login'
require 'swagger_client/models/message'
require 'swagger_client/models/message_response'
require 'swagger_client/models/messages_response'
require 'swagger_client/models/messages_response_messages'
require 'swagger_client/models/query'
require 'swagger_client/models/scheduled_batch_response'
require 'swagger_client/models/scheduled_message_response'
require 'swagger_client/models/send_message_response'
require 'swagger_client/models/token_response'
require 'swagger_client/models/extended_error_model'

# APIs
require 'swagger_client/api/auth_api'
require 'swagger_client/api/batch_messages_api'
require 'swagger_client/api/messages_api'
require 'swagger_client/api/utils_api'

module SwaggerClient
  class << self
    # Customize default settings for the SDK using block.
    #   SwaggerClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
